# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_core_frontend:
    pattern: /
    defaults: { _controller: sylius_sandbox_core.controller.frontend.main:indexAction }

sylius_sandbox_about:
    pattern: /about
    defaults: { _controller: sylius_sandbox_core.controller.frontend.main:aboutAction }

sylius_sandbox_core_frontend_product:
    resource: @SyliusSandboxBundle/Resources/config/routing/frontend/product.yml
    prefix: /products

sylius_sandbox_core_frontend_post:
    resource: @SyliusSandboxBundle/Resources/config/routing/frontend/post.yml
    prefix: /blog

sylius_sandbox_checkout_start:
    pattern: /checkout
    defaults: { _controller: sylius_flow.controller.process:startAction, scenarioAlias: 'sylius_sandbox_checkout' }

sylius_sandbox_checkout_display:
    pattern: /checkout/{stepName}
    defaults: { _controller: sylius_flow.controller.process:displayAction, scenarioAlias: 'sylius_sandbox_checkout' }

sylius_sandbox_checkout_forward:
    pattern: /checkout/{stepName}/forward
    defaults: { _controller: sylius_flow.controller.process:forwardAction, scenarioAlias: 'sylius_sandbox_checkout' }
