#!/usr/bin/env php
<?php

/*
 * This file is part of the Sylius sandbox application.
 *
 * (c) Paweł Jędrzejewski
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require_once __DIR__.'/../autoload.php';
require_once __DIR__.'/../SandboxKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new Sylius\SandboxKernel('development', true);
$application = new Application($kernel);
$application->run();
