# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_backend_tax_category_list:
    pattern: /
    defaults:
        _controller: sylius_taxation.controller.category:indexAction
        _template: SyliusSandboxBundle:Backend/TaxCategory:list.html.twig
        _sortable: true
        _sorting:
            name: desc

sylius_sandbox_backend_tax_category_create:
    pattern: /create
    defaults:
        _controller: sylius_taxation.controller.category:createAction
        _template: SyliusSandboxBundle:Backend/TaxCategory:create.html.twig
        _redirect: sylius_sandbox_backend_tax_category_list

sylius_sandbox_backend_tax_category_update:
    pattern: /update
    defaults:
        _controller: sylius_taxation.controller.category:updateAction
        _template: SyliusSandboxBundle:Backend/TaxCategory:update.html.twig
        _redirect: sylius_sandbox_backend_tax_category_list

sylius_sandbox_backend_tax_category_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_taxation.controller.category:deleteAction
        _redirect: sylius_sandbox_backend_tax_category_list
