# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_backend_user_list:
    pattern: /list
    defaults:
        _controller: sylius_user.controller.user:indexAction
        _template: SyliusSandboxBundle:Backend/User:list.html.twig
        _filterable: true
        _sortable: true
        _sorting:
            id: desc

sylius_sandbox_backend_user_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_user.controller.user:deleteAction
        _redirect: sylius_sandbox_backend_user_list

sylius_sandbox_backend_user_show:
    pattern: /{id}
    defaults:
        _controller: sylius_user.controller.user:showAction
        _template: SyliusSandboxBundle:Backend/User:show.html.twig
