# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_backend_variant_create:
    pattern: /create
    defaults:
        _controller: sylius_assortment.controller.variant:createAction
        _template: SyliusSandboxBundle:Backend/Variant:create.html.twig
        _redirect: sylius_sandbox_backend_variant_show

sylius_sandbox_backend_variant_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius_assortment.controller.variant:updateAction
        _template: SyliusSandboxBundle:Backend/Variant:update.html.twig
        _redirect: sylius_sandbox_backend_variant_show

sylius_sandbox_backend_variant_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_assortment.controller.variant:deleteAction
        _redirect: sylius_sandbox_backend_product_list

sylius_sandbox_backend_variant_generate:
    pattern: /generate
    defaults:
        _controller: sylius_assortment.controller.variant:generateAction
        _redirect: sylius_sandbox_backend_product_show

sylius_sandbox_backend_variant_show:
    pattern: /{id}
    defaults:
        _controller: sylius_assortment.controller.variant:showAction
        _template: SyliusSandboxBundle:Backend/Variant:show.html.twig
        productId: 'any' # Hacky hack...
